name = "rangefs-demo"
main = "src/worker.ts"
compatibility_date = "2025-12-18"
workers_dev = true

[[kv_namespaces]]
binding = "CONFIG"
id = "3db79397c0de484f8ac3f07e59cf57dd"
remote = true

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "rangefs"
remote = true

[[routes]]
pattern = "astro-100k.proc.io"
custom_domain = true

[observability]
[observability.logs]
enabled = true
head_sampling_rate = 1
invocation_logs = true
persist = false
