name = "rangefs-demo"
main = "src/worker.ts"
compatibility_date = "2025-12-18"
workers_dev = true

[[kv_namespaces]]
binding = "CONFIG"
id = "15ce64a84d2241a08fb345cc6d93d48b"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "rangefs"

[[routes]]
pattern = "astro-100k.proc.io"
custom_domain = true

[observability]
[observability.logs]
enabled = true
head_sampling_rate = 1
invocation_logs = true
persist = false
